name: "Run pipeline tests"

on:
  workflow_dispatch:

jobs:
  ui_pipeline_tests:
    name: "UI pipeline tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install package"
        run: yarn install
        working-directory: ./

      - name: "Run Tests"
        run: yarn test:demo-tests
        env:
          BROWSER: ${{ matrix.browser }}
          URL: https://the-internet.herokuapp.com/
      
      # -name: "Upload report"
      # if: always()
      # uses: actions/upload-artifact@v3
      # with:
      #   name: Reports
      #   retention-days: 5
      #   path: |
      #     packages/


